# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computers That Werk
email: info@computersthatwerk.com
description: Southwest Florida's premier IT Managed Service provider -- since 2014
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://computersthatwerk.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
