# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computers That Werk
email: info@computersthatwerk.com
description: Southwest Florida's premier IT Managed Service provider
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://computersthatwerk.com" # the base hostname & protocol for your site

authors:
  josh:
    name: Joshua Embrey
    display_name: Josh
    gravatar: 645286df9273b3b409c389c1079c2544
    email: jembrey@computersthatwerk.com
    web: http://computersthatwerk.com
    twitter: MrSchism
    github: MrSchism
  jorgen:
    name: Joseph Preston
    display_name: Joe
    gravatar: bb576d5e8aeab6272c52c341811b9c54
    email: jpreston@computersthatwerk.com
    web: http://computersthatwerk.com
    twitter: jpreston86
    github: jpreston86

# Build settings
markdown: kramdown
